[registry]
base_url = "https://some.registry.domain.tld/"
username = "someuser"
password = "the password"

[[rules]]
repo_pattern = ""
tag_pattern = "pr-"
max_tags = 0
overflow_max_age = "1d"
max_age = "1d"

[[rules]]
repo_pattern = ""
tag_pattern = "^[\\da-f]{64}$"
max_tags = 2
overflow_max_age = "3d"
max_age = "30d"
