name: CI

on:
  push:
    branches-ignore: ["gh-readonly-queue/**"]
  pull_request:
  merge_group:

jobs:
  cargo-tests:
    name: Lint & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Lint with clippy
        run: cargo clippy --locked --all-features -- -D warnings

      - name: Run tests
        run: cargo test --locked --all-features

  docker-build:
    name: Build image
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Attempt to build the image
        run: |
          docker build -t devops-automerge .

      - name: Test the image
        run: |
          # set up the container
          mkdir container-shared
          chmod 1777 container-shared
          docker run -dh devops-automerge --name devops-automerge-container --rm -v $PWD/container-shared:/host -v $PWD/config.test.toml:/config.toml:ro -e AUTOMERGE_CONFIG_FILE=/config.toml -p 8080:8080 --health-interval 5s devops-automerge
          # give it like 3 seconds
          sleep 3
          STOP_TOKEN="`uuidgen`"
          echo "::stop-commands::$STOP_TOKEN"
          # check status
          docker inspect devops-automerge-container -f '{{ .State.Status }}' | grep '^running$'
          FAILS=0
          while true
          do
            HEALTH=`docker inspect devops-automerge-container -f '{{ .State.Health.Status }}'`
            echo "$HEALTH"
            if [[ "$HEALTH" == "healthy" ]]
            then
                break
            else
              FAILS=$(($FAILS + 1))
              if [[ "$FAILS" -ge 5 ]]
              then
                  exit 1
              fi
            fi
            sleep 5
          done
          # run our own checks
          echo manual healthcheck TCP
          curl --fail-with-body -v --max-time 1 http://localhost:8080/health
          echo manual healthcheck unix
          curl --fail-with-body -v --max-time 1 --unix-socket ./container-shared/devops-automerge.sock http://localhost:8080/health
          echo main route check TCP
          curl --fail-with-body -v --max-time 1 http://localhost:8080/
          echo main route check unix
          curl --fail-with-body -v --max-time 1 --unix-socket ./container-shared/devops-automerge.sock http://localhost:8080/
          # finish
          docker stop devops-automerge-container
          echo "::$STOP_TOKEN::"

  bare-metal-build:
    name: Build & test rust executable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        run: cargo build --release --locked

      - name: Run & check compiled executable
        timeout-minutes: 1
        if: false
        run: |
          mkdir host
          STOP_TOKEN="`uuidgen`"
          echo "::stop-commands::$STOP_TOKEN"
          # start the server
          echo starting server
          AUTOMERGE_CONFIG_FILE=./config.test.toml ./target/release/devops-automerge &
          # give it some time
          sleep 1
          # run built-in healthchecks
          echo built-in healthchecks
          AUTOMERGE_CONFIG_FILE=./config.test.toml ./target/release/devops-automerge health
          # manual healthchecks
          echo manual healthcheck TCP
          curl --fail-with-body -v --max-time 1 http://localhost:8080/health
          echo manual healthcheck unix
          curl --fail-with-body -v --max-time 1 --unix-socket ./host/devops-automerge.sock http://localhost:8080/health
          echo main route check TCP
          curl --fail-with-body -v --max-time 1 http://localhost:8080/
          echo main route check unix
          curl --fail-with-body -v --max-time 1 --unix-socket ./host/devops-automerge.sock http://localhost:8080/
          # interrupt the server and join
          echo checks done, stopping server
          kill -INT %1
          wait
          echo "::$STOP_TOKEN::"
